"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from prime import get_n_divisors

def get_triangle(n):
    if n < 1 or int(n) != n:
        raise ValueError("n must be a positive integer")
    return (n*(n+1)) >> 1

i = 1
current_divisors = (get_n_divisors(i >> 1)*get_n_divisors(i+1) if i % 2 == 0 else
                    get_n_divisors(i)*get_n_divisors((i+1) >> 1))
while current_divisors <= 500:
    i += 1
    current_divisors = (get_n_divisors(i >> 1)*get_n_divisors(i+1) if i % 2 == 0 else
                    get_n_divisors(i)*get_n_divisors((i+1) >> 1))
print(get_triangle(i))